export enum Permission {
  USERS_READ = 'users.read',
  USERS_CREATE = 'users.create',
  USERS_UPDATE = 'users.update',
  USERS_DELETE = 'users.delete',
  DEPARTMENTS_READ = 'departments.read',
  DEPARTMENTS_CREATE = 'departments.create',
  DEPARTMENTS_UPDATE = 'departments.update',
  DEPARTMENTS_DELETE = 'departments.delete',
  DOCUMENTS_READ = 'documents.read',
  DOCUMENTS_CREATE = 'documents.create',
  DOCUMENTS_UPDATE = 'documents.update',
  DOCUMENTS_DELETE = 'documents.delete',
  DOCUMENTS_ROUTE_EXECUTE = 'documents.route.execute',
  DOCUMENTS_ARCHIVE = 'documents.archive',
  DOCUMENTS_AUDIT_READ = 'documents.audit.read',
  DOCUMENTS_REGISTER = 'documents.register',
  DOCUMENTS_ALERTS_READ = 'documents.alerts.read',
  DOCUMENTS_ALERTS_MANAGE = 'documents.alerts.manage',
  DOCUMENTS_TEMPLATES_READ = 'documents.templates.read',
  DOCUMENTS_TEMPLATES_WRITE = 'documents.templates.write',
  DOCUMENTS_ROUTE_TEMPLATES_READ = 'documents.route.templates.read',
  DOCUMENTS_ROUTE_TEMPLATES_WRITE = 'documents.route.templates.write',
  TASKS_READ = 'tasks.read',
  TASKS_CREATE = 'tasks.create',
  TASKS_UPDATE = 'tasks.update',
  TASKS_DELETE = 'tasks.delete',
  TASKS_ASSIGN = 'tasks.assign',
  ANALYTICS_READ = 'analytics.read',
  ANALYTICS_WRITE = 'analytics.write',
  REPORTS_READ = 'reports.read',
  REPORTS_GENERATE = 'reports.generate',
  GIS_READ = 'gis.read',
  GIS_WRITE = 'gis.write',
  FILES_READ = 'files.read',
  FILES_WRITE = 'files.write',
  FILES_DELETE = 'files.delete',
  CHAT_READ = 'chat.read',
  CHAT_WRITE = 'chat.write',
  CALLS_READ = 'calls.read',
  CALLS_WRITE = 'calls.write',

  // Task Management (enterprise)
  TM_TASKS_READ              = 'task_management.tasks.read',
  TM_TASKS_CREATE            = 'task_management.tasks.create',
  TM_TASKS_UPDATE            = 'task_management.tasks.update',
  TM_TASKS_DELETE            = 'task_management.tasks.delete',
  TM_TASKS_ASSIGN            = 'task_management.tasks.assign',
  TM_TASKS_DELEGATE          = 'task_management.tasks.delegate',
  TM_TASKS_CLOSE             = 'task_management.tasks.close',
  TM_BOARDS_READ             = 'task_management.boards.read',
  TM_BOARDS_MANAGE           = 'task_management.boards.manage',
  TM_REPORTS_READ            = 'task_management.reports.read',
  TM_ESCALATION_MANAGE       = 'task_management.escalation.manage',
}

export type PermissionType = `${Permission}`;
