import { Role } from '../../users/enums/role.enum';
import { Permission, PermissionType } from './permission.type';

const ALL_PERMISSIONS = Object.values(Permission) as PermissionType[];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, PermissionType[]> = {
  [Role.Admin]: ALL_PERMISSIONS,
  [Role.Chairperson]: [
    Permission.USERS_READ,
    Permission.DEPARTMENTS_READ,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_CREATE,
    Permission.DOCUMENTS_UPDATE,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ARCHIVE,
    Permission.DOCUMENTS_AUDIT_READ,
    Permission.DOCUMENTS_REGISTER,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.DOCUMENTS_ALERTS_MANAGE,
    Permission.DOCUMENTS_TEMPLATES_READ,
    Permission.DOCUMENTS_TEMPLATES_WRITE,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_READ,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_WRITE,
    Permission.TASKS_READ,
    Permission.TASKS_CREATE,
    Permission.TASKS_UPDATE,
    Permission.TASKS_ASSIGN,
    Permission.ANALYTICS_READ,
    Permission.REPORTS_READ,
    Permission.REPORTS_GENERATE,
    Permission.GIS_READ,
    Permission.GIS_WRITE,
    Permission.FILES_READ,
    Permission.FILES_WRITE,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.FirstDeputy]: [
    Permission.USERS_READ,
    Permission.DEPARTMENTS_READ,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_CREATE,
    Permission.DOCUMENTS_UPDATE,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ARCHIVE,
    Permission.DOCUMENTS_AUDIT_READ,
    Permission.DOCUMENTS_REGISTER,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.DOCUMENTS_ALERTS_MANAGE,
    Permission.DOCUMENTS_TEMPLATES_READ,
    Permission.DOCUMENTS_TEMPLATES_WRITE,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_READ,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_WRITE,
    Permission.TASKS_READ,
    Permission.TASKS_CREATE,
    Permission.TASKS_UPDATE,
    Permission.TASKS_ASSIGN,
    Permission.ANALYTICS_READ,
    Permission.REPORTS_READ,
    Permission.REPORTS_GENERATE,
    Permission.GIS_READ,
    Permission.GIS_WRITE,
    Permission.FILES_READ,
    Permission.FILES_WRITE,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.Deputy]: [
    Permission.USERS_READ,
    Permission.DEPARTMENTS_READ,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_CREATE,
    Permission.DOCUMENTS_UPDATE,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ARCHIVE,
    Permission.DOCUMENTS_AUDIT_READ,
    Permission.DOCUMENTS_REGISTER,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.DOCUMENTS_ALERTS_MANAGE,
    Permission.DOCUMENTS_TEMPLATES_READ,
    Permission.DOCUMENTS_TEMPLATES_WRITE,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_READ,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_WRITE,
    Permission.TASKS_READ,
    Permission.TASKS_CREATE,
    Permission.TASKS_UPDATE,
    Permission.TASKS_ASSIGN,
    Permission.ANALYTICS_READ,
    Permission.REPORTS_READ,
    Permission.REPORTS_GENERATE,
    Permission.GIS_READ,
    Permission.GIS_WRITE,
    Permission.FILES_READ,
    Permission.FILES_WRITE,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.DepartmentHead]: [
    Permission.USERS_READ,
    Permission.DEPARTMENTS_READ,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_CREATE,
    Permission.DOCUMENTS_UPDATE,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ARCHIVE,
    Permission.DOCUMENTS_AUDIT_READ,
    Permission.DOCUMENTS_REGISTER,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.DOCUMENTS_ALERTS_MANAGE,
    Permission.DOCUMENTS_TEMPLATES_READ,
    Permission.DOCUMENTS_TEMPLATES_WRITE,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_READ,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_WRITE,
    Permission.TASKS_READ,
    Permission.TASKS_CREATE,
    Permission.TASKS_UPDATE,
    Permission.TASKS_ASSIGN,
    Permission.ANALYTICS_READ,
    Permission.REPORTS_READ,
    Permission.REPORTS_GENERATE,
    Permission.GIS_READ,
    Permission.GIS_WRITE,
    Permission.FILES_READ,
    Permission.FILES_WRITE,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.DivisionHead]: [
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.TASKS_READ,
    Permission.ANALYTICS_READ,
    Permission.GIS_READ,
    Permission.FILES_READ,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.Chancellery]: [
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_CREATE,
    Permission.DOCUMENTS_UPDATE,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ARCHIVE,
    Permission.DOCUMENTS_AUDIT_READ,
    Permission.DOCUMENTS_REGISTER,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.DOCUMENTS_ALERTS_MANAGE,
    Permission.DOCUMENTS_TEMPLATES_READ,
    Permission.DOCUMENTS_TEMPLATES_WRITE,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_READ,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_WRITE,
    Permission.TASKS_READ,
    Permission.TASKS_CREATE,
    Permission.TASKS_UPDATE,
    Permission.TASKS_ASSIGN,
    Permission.REPORTS_READ,
    Permission.REPORTS_GENERATE,
    Permission.FILES_READ,
    Permission.FILES_WRITE,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.Employee]: [
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.TASKS_READ,
    Permission.ANALYTICS_READ,
    Permission.GIS_READ,
    Permission.FILES_READ,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.Analyst]: [
    Permission.ANALYTICS_READ,
    Permission.REPORTS_READ,
    Permission.REPORTS_GENERATE,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_AUDIT_READ,
    Permission.GIS_READ,
    Permission.GIS_WRITE,
    Permission.FILES_READ,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.Manager]: [
    Permission.USERS_READ,
    Permission.DEPARTMENTS_READ,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_CREATE,
    Permission.DOCUMENTS_UPDATE,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ARCHIVE,
    Permission.DOCUMENTS_AUDIT_READ,
    Permission.DOCUMENTS_REGISTER,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.DOCUMENTS_ALERTS_MANAGE,
    Permission.DOCUMENTS_TEMPLATES_READ,
    Permission.DOCUMENTS_TEMPLATES_WRITE,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_READ,
    Permission.DOCUMENTS_ROUTE_TEMPLATES_WRITE,
    Permission.TASKS_READ,
    Permission.TASKS_CREATE,
    Permission.TASKS_UPDATE,
    Permission.TASKS_ASSIGN,
    Permission.ANALYTICS_READ,
    Permission.REPORTS_READ,
    Permission.REPORTS_GENERATE,
    Permission.GIS_READ,
    Permission.GIS_WRITE,
    Permission.FILES_READ,
    Permission.FILES_WRITE,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
  [Role.Regular]: [
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_ROUTE_EXECUTE,
    Permission.DOCUMENTS_ALERTS_READ,
    Permission.TASKS_READ,
    Permission.ANALYTICS_READ,
    Permission.GIS_READ,
    Permission.FILES_READ,
    Permission.CHAT_READ,
    Permission.CHAT_WRITE,
    Permission.CALLS_READ,
    Permission.CALLS_WRITE,
  ],
};

export function getRolePermissions(role: Role): PermissionType[] {
  return DEFAULT_ROLE_PERMISSIONS[role] ?? [];
}

export function resolveUserPermissions(
  role: Role,
  customPermissions: PermissionType[] = [],
): PermissionType[] {
  return [...new Set([...getRolePermissions(role), ...customPermissions])];
}
