export const PERMISSIONS = [
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'departments.read',
  'departments.create',
  'departments.update',
  'departments.delete',
  'documents.read',
  'documents.create',
  'documents.update',
  'documents.delete',
  'documents.route.execute',
  'documents.archive',
  'documents.audit.read',
  'documents.register',
  'documents.alerts.read',
  'documents.alerts.manage',
  'documents.templates.read',
  'documents.templates.write',
  'documents.route.templates.read',
  'documents.route.templates.write',
  'tasks.read',
  'tasks.create',
  'tasks.update',
  'tasks.delete',
  'tasks.assign',
  'analytics.read',
  'analytics.write',
  'reports.read',
  'reports.generate',
  'gis.read',
  'gis.write',
  'files.read',
  'files.write',
  'files.delete',
  'chat.read',
  'chat.write',
  'calls.read',
  'calls.write',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

