import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1771794508244 implements MigrationInterface {
    name = 'AutoMigration1771794508244'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_372ba8832ed6f97bccd2d696cbd"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b"`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP CONSTRAINT "FK_93e336d1c079edb2cecd9c8f599"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_9be04828b2f746bc83268766626"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_9d207f670875c015e66e25bfe0b"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_afd2c87bee70dd5557f48911e66"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_ed83132cc853103ac2acd948992"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_f4cb489461bc751498a28852356"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_fe49ddbcf2436d7a6fbbbc71293"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_4bc1db1f4f34ec9415acd88afdb"`);
        await queryRunner.query(`ALTER TABLE "file_links" DROP CONSTRAINT "FK_c78a61293671a996c88094cc56f"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_707a5642f0c835dbc89e603cbd5"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_2c2540c0d341c8e20048681f4c3"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_1d312a094ffbc86e70c8893854d"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_9030ba74cb54f3c65fcf309570f"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_8946ca43f41b4fcbc725a7f8d1c"`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" DROP CONSTRAINT "FK_edm_document_kinds_updated_by"`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" DROP CONSTRAINT "FK_edm_document_kinds_created_by"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_edm_documents_document_kind"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_deed290f1b3b94f901d321a6781"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_b8bf993005538aed05a0903c182"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_e40e6c1adb9151892020545d241"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "FK_b1f120110cbed36432933d387d4"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_fba02ee9095f83950220f0731cf"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_0f6a636b1197bde1cbf3ad7e0cd"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_d4cfe44c70962730c5e6a4f874d"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_fd49bbbbbc0f857cb04b54af529"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_d62a0d61aa4521efb406d53b2c9"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_55c90edc007fd99b0bc0e99939a"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_bb080db9f06e15e64aae9eb3a20"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_cb9eaa5a2ad3500d56acd4e1788"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_bdaabe55e703ab72a6166ccc2e2"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_00e35de7efa8506d0594dad3a99"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_8b633284d47de67800345e8dfba"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_0b3ae928b45b6b2689ed7d6c074"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_fc2b6c8fb9bb600ea350834d921"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_a0683e3c4d5d9c260c23670b407"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_0e52f75963f6396469f374fc62a"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_b84c416889d4b932181651fcfe7"`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" DROP CONSTRAINT "FK_1dd9e424c2049d801226d7b093d"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_24a226d1434cd9a9748d5f11959"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_2084e87705a9e82da5b6155b34b"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_22152d6ddc87213d39d48cf02d4"`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" DROP CONSTRAINT "FK_c7cfc526890ae8386b480349120"`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" DROP CONSTRAINT "FK_24ac4f04dd37d321ee7f50b8b96"`);
        await queryRunner.query(`ALTER TABLE "disasters" DROP CONSTRAINT "FK_c7a8da7d338b26a90d37eb45fa5"`);
        await queryRunner.query(`ALTER TABLE "disasters" DROP CONSTRAINT "FK_178367b82fb965637d69222189e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DEPARTMENTS_PARENT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DEPARTMENTS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORG_UNITS_PARENT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORG_UNITS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORG_UNITS_PATH_GIST"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_DEPARTMENT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_ROLE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_IS_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_BUSINESS_ROLE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_ORG_UNIT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_DEPT_ACTIVE_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_DEPT_ROLE_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_CHANGE_AUDIT_ACTOR_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_CHANGE_AUDIT_TARGET_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_CHANGE_AUDIT_ACTION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_CHANGE_AUDIT_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_CHANGE_AUDIT_TARGET_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BULK_IMPORT_OPS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BULK_IMPORT_OPS_ACTOR_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BULK_IMPORT_OPS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_CREATOR_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_RECEIVER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_RECEIVER_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_CREATOR_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIS_LAYERS_DEPT_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIS_LAYERS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIS_FEATURES_STATUS_SEVERITY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIS_FEATURES_DEPT_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIS_FEATURES_LAT_LNG"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIS_FEATURES_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIS_FEATURES_LAYER_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_OWNER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_DEPARTMENT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_OWNER_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_DEPT_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_LINKS_FILE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_LINKS_RESOURCE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_ACCESS_AUDIT_FILE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_ACCESS_AUDIT_ACTOR_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_ACCESS_AUDIT_ACTION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_ACCESS_AUDIT_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_ACCESS_AUDIT_USER_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILE_ACCESS_AUDIT_FILE_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DELEGATION_DELEGATE_VALIDITY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DELEGATION_DELEGATOR_VALIDITY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DELEGATION_SCOPE_ORG_UNIT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_DEPARTMENT_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_CREATOR_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_EXTERNAL_NUMBER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_DELETED_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_DEPT_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_TYPE_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_CURRENT_ROUTE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edm_documents_document_kind"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_DOCUMENT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_STATE_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_DOCUMENT_VERSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_STAGE_ROUTE_ORDER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_STAGE_ROUTE_STATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_STAGE_ASSIGNEE_USER_STATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_STAGE_STATE_DUE_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_STAGE_ASSIGNEE_USER_STATE_DUE_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_STAGE_ASSIGNEE_DEPT_STATE_DUE_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ACTION_STAGE_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ACTION_DOCUMENT_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ACTION_ACTOR_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_SAVED_FILTER_USER_SCOPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_SAVED_FILTER_USER_DEFAULT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_SAVED_FILTER_USER_NAME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_TEMPLATE_STAGE_TEMPLATE_ORDER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_TEMPLATE_SCOPE_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_TEMPLATE_DEPARTMENT_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ROUTE_TEMPLATE_ACTIVE_UPDATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_REG_JOURNAL_TYPE_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_REG_JOURNAL_REGISTERED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_REG_JOURNAL_TYPE_STATUS_REGISTERED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_TIMELINE_DOCUMENT_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_TIMELINE_THREAD_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_TIMELINE_EVENT_TYPE_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOCUMENT_TEMPLATE_FIELD_TEMPLATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOCUMENT_TEMPLATE_FIELD_SORT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOCUMENT_TEMPLATE_SCOPE_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOCUMENT_TEMPLATE_DEPARTMENT_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOCUMENT_TEMPLATE_ACTIVE_UPDATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_TASK_LINK_DOCUMENT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_DOC_TASK_LINK_TASK"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_REPLY_DOCUMENT_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_REPLY_THREAD_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_REGISTRY_SCOPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ALERT_RECIPIENT_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ALERT_STAGE_KIND"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ALERT_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ALERT_RECIPIENT_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EDM_ALERT_RECIPIENT_KIND_STATUS_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCUMENTS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCUMENTS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCUMENTS_DEPARTMENT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCUMENTS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCUMENTS_SENDER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCUMENTS_RECEIVER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_AUDIT_LOGS_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_AUDIT_LOGS_ACTION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_AUDIT_LOGS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_AUDIT_USER_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DISASTER_TYPES_CATEGORY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DISASTERS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DISASTERS_SEVERITY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DISASTERS_DEPARTMENT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DISASTERS_CREATED_AT"`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP CONSTRAINT "CHK_ORG_UNITS_TYPE"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "CHK_IAM_DELEGATIONS_SCOPE_TYPE"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "CHK_IAM_DELEGATIONS_STATUS"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "CHK_IAM_DELEGATIONS_VALID_RANGE"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "CHK_IAM_DELEGATIONS_DISTINCT_USERS"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "CHK_EDM_DOCUMENT_STATUS"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "CHK_EDM_DOCUMENT_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "CHK_EDM_DOCUMENT_CONFIDENTIALITY"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "CHK_EDM_ROUTE_STATE"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "CHK_EDM_ROUTE_COMPLETION_POLICY"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "CHK_EDM_STAGE_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "CHK_EDM_ASSIGNEE_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "CHK_EDM_STAGE_STATE"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "CHK_EDM_ASSIGNEE_CONSISTENCY"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "CHK_EDM_ACTION"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "CHK_EDM_ACTION_RESULT_STATE"`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" DROP CONSTRAINT "CHK_EDM_SAVED_FILTER_SCOPE"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_STAGE_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_ASSIGNEE_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_ASSIGNEE_CONSISTENCY"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_SCOPE_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "CHK_EDM_REG_JOURNAL_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "CHK_EDM_REG_JOURNAL_STATUS"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "CHK_EDM_TIMELINE_EVENT_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" DROP CONSTRAINT "CHK_EDM_DOCUMENT_TEMPLATE_FIELD_KEY"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "CHK_EDM_DOCUMENT_TEMPLATE_DOC_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "CHK_EDM_DOCUMENT_TEMPLATE_SCOPE_TYPE"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "CHK_EDM_ALERT_KIND"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "CHK_EDM_ALERT_STATUS"`);
        await queryRunner.query(`ALTER TABLE "iam_business_roles" DROP CONSTRAINT "CHK_IAM_BUSINESS_ROLES_DEFAULT_SCOPE"`);
        await queryRunner.query(`ALTER TABLE "file_links" DROP CONSTRAINT "UQ_FILE_LINK_RESOURCE"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "UQ_EDM_ROUTE_DOCUMENT_VERSION"`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" DROP CONSTRAINT "UQ_EDM_DOCUMENT_TEMPLATE_FIELD"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "UQ_EDM_DOCUMENT_TASK_LINK"`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" DROP CONSTRAINT "UQ_EDM_REGISTRY_SCOPE"`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" SERIAL NOT NULL, "room" character varying(100) NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "sender_id" integer, CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calls" ("id" SERIAL NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "has_video" boolean NOT NULL DEFAULT false, "started_at" TIMESTAMP WITH TIME ZONE, "ended_at" TIMESTAMP WITH TIME ZONE, "duration_sec" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "initiator_id" integer, "receiver_id" integer, CONSTRAINT "PK_d9171d91f8dd1a649659f1b6a20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "type" "public"."departments_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD "path" character varying`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'new'`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "receiver_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "owner_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "file_links" DROP CONSTRAINT "FK_64db2f1947f0f95e79d8659207f"`);
        await queryRunner.query(`ALTER TABLE "file_links" ALTER COLUMN "file_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "file_links" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "file_access_audit" DROP CONSTRAINT "FK_d363482d039e3b7e5ab863c5d9e"`);
        await queryRunner.query(`ALTER TABLE "file_access_audit" ALTER COLUMN "file_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ALTER COLUMN "delegator_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ALTER COLUMN "delegate_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ALTER COLUMN "department_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "FK_83e4e52bfe54b62e2fec2844563"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ALTER COLUMN "document_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_315b745a0b22dbc26cdb33ea596"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ALTER COLUMN "route_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_4b15bfe33b4bdc4863e7484b98a"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_a66554a9bcd873cfc3b8ccbb06b"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ALTER COLUMN "stage_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ALTER COLUMN "document_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ALTER COLUMN "actor_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" DROP CONSTRAINT "FK_05caf390cbd40baffad56a576a8"`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_fdddb7bf3ded6561a76f8d96a2a"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ALTER COLUMN "template_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "UQ_EDM_REG_JOURNAL_NUMBER"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ALTER COLUMN "document_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_6208dbc3cbbe81c855d0abd402f"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_af2ff1dc4188f1dc0f122a2ca37"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ALTER COLUMN "document_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ALTER COLUMN "actor_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" DROP CONSTRAINT "FK_3ce49798d851e7a8368881d2361"`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" ALTER COLUMN "template_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_0eb30ac5f71609857a202455c05"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_56724b2f6e7a29d26a76752de90"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ALTER COLUMN "document_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ALTER COLUMN "task_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_a073b7c4420bd01bbd3c1cb5b7f"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_cd7b226c0eea663dd9b2d12917a"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_3d4f8001664e4a32d09ae6096da"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ALTER COLUMN "document_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ALTER COLUMN "timeline_event_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ALTER COLUMN "sender_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" ALTER COLUMN "department_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_eda2a65b0f125f7c6ae0b7b6039"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_c3dfcf1e88da3a9ad63c41809b0"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_dc16f5fd345854683468625bad9"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ALTER COLUMN "document_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ALTER COLUMN "stage_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ALTER COLUMN "recipient_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "type" "public"."documents_type_enum" NOT NULL DEFAULT 'internal'`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "status" "public"."documents_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "FK_1bbe5812d6dadf6a5e18602c1c3"`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "FK_2aec8289d19d36055fb99f98cf9"`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "UQ_BUSINESS_ROLE_PERMISSION_PROFILE_PAIR"`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ALTER COLUMN "business_role_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ALTER COLUMN "permission_profile_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disaster_types" DROP CONSTRAINT "FK_87225b03132d651c46ead3b59be"`);
        await queryRunner.query(`ALTER TABLE "disaster_types" ALTER COLUMN "category_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disasters" DROP COLUMN "severity"`);
        await queryRunner.query(`ALTER TABLE "disasters" ADD "severity" "public"."disasters_severity_enum" NOT NULL DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "disasters" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "disasters" ADD "status" "public"."disasters_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "UQ_BUSINESS_ROLE_PERMISSION_PROFILE_PAIR" UNIQUE ("business_role_id", "permission_profile_id")`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b" FOREIGN KEY ("parent_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_372ba8832ed6f97bccd2d696cbd" FOREIGN KEY ("chief_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD CONSTRAINT "FK_93e336d1c079edb2cecd9c8f599" FOREIGN KEY ("parent_id") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_afd2c87bee70dd5557f48911e66" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_9d207f670875c015e66e25bfe0b" FOREIGN KEY ("org_unit_id") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_f4cb489461bc751498a28852356" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_ed83132cc853103ac2acd948992" FOREIGN KEY ("receiver_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_4bc1db1f4f34ec9415acd88afdb" FOREIGN KEY ("owner_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_fe49ddbcf2436d7a6fbbbc71293" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_links" ADD CONSTRAINT "FK_64db2f1947f0f95e79d8659207f" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_links" ADD CONSTRAINT "FK_c78a61293671a996c88094cc56f" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_access_audit" ADD CONSTRAINT "FK_d363482d039e3b7e5ab863c5d9e" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_8946ca43f41b4fcbc725a7f8d1c" FOREIGN KEY ("delegator_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_9030ba74cb54f3c65fcf309570f" FOREIGN KEY ("delegate_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_1d312a094ffbc86e70c8893854d" FOREIGN KEY ("scope_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_707a5642f0c835dbc89e603cbd5" FOREIGN KEY ("scope_org_unit_id") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_2c2540c0d341c8e20048681f4c3" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" ADD CONSTRAINT "FK_904360fe69c9f60910fb7cef217" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" ADD CONSTRAINT "FK_3bcd0bf9b7cb046ce5d71b057a6" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_e40e6c1adb9151892020545d241" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_b8bf993005538aed05a0903c182" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_6d875d41ecb59952cf306d1228d" FOREIGN KEY ("document_kind_id") REFERENCES "edm_document_kinds"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_deed290f1b3b94f901d321a6781" FOREIGN KEY ("current_route_id") REFERENCES "edm_document_routes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "FK_83e4e52bfe54b62e2fec2844563" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "FK_b1f120110cbed36432933d387d4" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_315b745a0b22dbc26cdb33ea596" FOREIGN KEY ("route_id") REFERENCES "edm_document_routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_0f6a636b1197bde1cbf3ad7e0cd" FOREIGN KEY ("assignee_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_fba02ee9095f83950220f0731cf" FOREIGN KEY ("assignee_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_4b15bfe33b4bdc4863e7484b98a" FOREIGN KEY ("stage_id") REFERENCES "edm_route_stages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_a66554a9bcd873cfc3b8ccbb06b" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_fd49bbbbbc0f857cb04b54af529" FOREIGN KEY ("actor_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_d4cfe44c70962730c5e6a4f874d" FOREIGN KEY ("on_behalf_of_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" ADD CONSTRAINT "FK_05caf390cbd40baffad56a576a8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_fdddb7bf3ded6561a76f8d96a2a" FOREIGN KEY ("template_id") REFERENCES "edm_route_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_55c90edc007fd99b0bc0e99939a" FOREIGN KEY ("assignee_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_d62a0d61aa4521efb406d53b2c9" FOREIGN KEY ("assignee_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_bdaabe55e703ab72a6166ccc2e2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_cb9eaa5a2ad3500d56acd4e1788" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_bb080db9f06e15e64aae9eb3a20" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_0b3ae928b45b6b2689ed7d6c074" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_8b633284d47de67800345e8dfba" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_00e35de7efa8506d0594dad3a99" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_6208dbc3cbbe81c855d0abd402f" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_af2ff1dc4188f1dc0f122a2ca37" FOREIGN KEY ("actor_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" ADD CONSTRAINT "FK_3ce49798d851e7a8368881d2361" FOREIGN KEY ("template_id") REFERENCES "edm_document_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_0e52f75963f6396469f374fc62a" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_a0683e3c4d5d9c260c23670b407" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_fc2b6c8fb9bb600ea350834d921" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_0eb30ac5f71609857a202455c05" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_56724b2f6e7a29d26a76752de90" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_b84c416889d4b932181651fcfe7" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_a073b7c4420bd01bbd3c1cb5b7f" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_cd7b226c0eea663dd9b2d12917a" FOREIGN KEY ("timeline_event_id") REFERENCES "edm_document_timeline_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_3d4f8001664e4a32d09ae6096da" FOREIGN KEY ("sender_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" ADD CONSTRAINT "FK_1dd9e424c2049d801226d7b093d" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_eda2a65b0f125f7c6ae0b7b6039" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_c3dfcf1e88da3a9ad63c41809b0" FOREIGN KEY ("stage_id") REFERENCES "edm_route_stages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_dc16f5fd345854683468625bad9" FOREIGN KEY ("recipient_user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_22152d6ddc87213d39d48cf02d4" FOREIGN KEY ("sender_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_2084e87705a9e82da5b6155b34b" FOREIGN KEY ("receiver_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_24a226d1434cd9a9748d5f11959" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718" FOREIGN KEY ("sender_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_b29f8b8864e7ce1968e02c89122" FOREIGN KEY ("initiator_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_6f6f829995f18781a4043e5bda9" FOREIGN KEY ("receiver_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "FK_1bbe5812d6dadf6a5e18602c1c3" FOREIGN KEY ("business_role_id") REFERENCES "iam_business_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "FK_2aec8289d19d36055fb99f98cf9" FOREIGN KEY ("permission_profile_id") REFERENCES "permission_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disaster_types" ADD CONSTRAINT "FK_87225b03132d651c46ead3b59be" FOREIGN KEY ("category_id") REFERENCES "disaster_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disasters" ADD CONSTRAINT "FK_178367b82fb965637d69222189e" FOREIGN KEY ("type_id") REFERENCES "disaster_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disasters" ADD CONSTRAINT "FK_c7a8da7d338b26a90d37eb45fa5" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "disasters" DROP CONSTRAINT "FK_c7a8da7d338b26a90d37eb45fa5"`);
        await queryRunner.query(`ALTER TABLE "disasters" DROP CONSTRAINT "FK_178367b82fb965637d69222189e"`);
        await queryRunner.query(`ALTER TABLE "disaster_types" DROP CONSTRAINT "FK_87225b03132d651c46ead3b59be"`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "FK_2aec8289d19d36055fb99f98cf9"`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "FK_1bbe5812d6dadf6a5e18602c1c3"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_6f6f829995f18781a4043e5bda9"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_b29f8b8864e7ce1968e02c89122"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_24a226d1434cd9a9748d5f11959"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_2084e87705a9e82da5b6155b34b"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_22152d6ddc87213d39d48cf02d4"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_dc16f5fd345854683468625bad9"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_c3dfcf1e88da3a9ad63c41809b0"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_eda2a65b0f125f7c6ae0b7b6039"`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" DROP CONSTRAINT "FK_1dd9e424c2049d801226d7b093d"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_3d4f8001664e4a32d09ae6096da"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_cd7b226c0eea663dd9b2d12917a"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_a073b7c4420bd01bbd3c1cb5b7f"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_b84c416889d4b932181651fcfe7"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_56724b2f6e7a29d26a76752de90"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_0eb30ac5f71609857a202455c05"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_fc2b6c8fb9bb600ea350834d921"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_a0683e3c4d5d9c260c23670b407"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_0e52f75963f6396469f374fc62a"`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" DROP CONSTRAINT "FK_3ce49798d851e7a8368881d2361"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_af2ff1dc4188f1dc0f122a2ca37"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_6208dbc3cbbe81c855d0abd402f"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_00e35de7efa8506d0594dad3a99"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_8b633284d47de67800345e8dfba"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_0b3ae928b45b6b2689ed7d6c074"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_bb080db9f06e15e64aae9eb3a20"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_cb9eaa5a2ad3500d56acd4e1788"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_bdaabe55e703ab72a6166ccc2e2"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_d62a0d61aa4521efb406d53b2c9"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_55c90edc007fd99b0bc0e99939a"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_fdddb7bf3ded6561a76f8d96a2a"`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" DROP CONSTRAINT "FK_05caf390cbd40baffad56a576a8"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_d4cfe44c70962730c5e6a4f874d"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_fd49bbbbbc0f857cb04b54af529"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_a66554a9bcd873cfc3b8ccbb06b"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_4b15bfe33b4bdc4863e7484b98a"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_fba02ee9095f83950220f0731cf"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_0f6a636b1197bde1cbf3ad7e0cd"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_315b745a0b22dbc26cdb33ea596"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "FK_b1f120110cbed36432933d387d4"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "FK_83e4e52bfe54b62e2fec2844563"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_deed290f1b3b94f901d321a6781"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_6d875d41ecb59952cf306d1228d"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_b8bf993005538aed05a0903c182"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_e40e6c1adb9151892020545d241"`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" DROP CONSTRAINT "FK_3bcd0bf9b7cb046ce5d71b057a6"`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" DROP CONSTRAINT "FK_904360fe69c9f60910fb7cef217"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_2c2540c0d341c8e20048681f4c3"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_707a5642f0c835dbc89e603cbd5"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_1d312a094ffbc86e70c8893854d"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_9030ba74cb54f3c65fcf309570f"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_8946ca43f41b4fcbc725a7f8d1c"`);
        await queryRunner.query(`ALTER TABLE "file_access_audit" DROP CONSTRAINT "FK_d363482d039e3b7e5ab863c5d9e"`);
        await queryRunner.query(`ALTER TABLE "file_links" DROP CONSTRAINT "FK_c78a61293671a996c88094cc56f"`);
        await queryRunner.query(`ALTER TABLE "file_links" DROP CONSTRAINT "FK_64db2f1947f0f95e79d8659207f"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_fe49ddbcf2436d7a6fbbbc71293"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_4bc1db1f4f34ec9415acd88afdb"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_ed83132cc853103ac2acd948992"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_f4cb489461bc751498a28852356"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_9d207f670875c015e66e25bfe0b"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_afd2c87bee70dd5557f48911e66"`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP CONSTRAINT "FK_93e336d1c079edb2cecd9c8f599"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_372ba8832ed6f97bccd2d696cbd"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b"`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "UQ_BUSINESS_ROLE_PERMISSION_PROFILE_PAIR"`);
        await queryRunner.query(`ALTER TABLE "disasters" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "disasters" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "disasters" DROP COLUMN "severity"`);
        await queryRunner.query(`ALTER TABLE "disasters" ADD "severity" character varying NOT NULL DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "disaster_types" ALTER COLUMN "category_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disaster_types" ADD CONSTRAINT "FK_87225b03132d651c46ead3b59be" FOREIGN KEY ("category_id") REFERENCES "disaster_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ALTER COLUMN "permission_profile_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ALTER COLUMN "business_role_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "UQ_BUSINESS_ROLE_PERMISSION_PROFILE_PAIR" UNIQUE ("business_role_id", "permission_profile_id")`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "FK_2aec8289d19d36055fb99f98cf9" FOREIGN KEY ("permission_profile_id") REFERENCES "permission_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "FK_1bbe5812d6dadf6a5e18602c1c3" FOREIGN KEY ("business_role_id") REFERENCES "iam_business_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "status" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "type" character varying NOT NULL DEFAULT 'internal'`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ALTER COLUMN "recipient_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ALTER COLUMN "stage_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ALTER COLUMN "document_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_dc16f5fd345854683468625bad9" FOREIGN KEY ("recipient_user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_c3dfcf1e88da3a9ad63c41809b0" FOREIGN KEY ("stage_id") REFERENCES "edm_route_stages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_eda2a65b0f125f7c6ae0b7b6039" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" ALTER COLUMN "department_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ALTER COLUMN "sender_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ALTER COLUMN "timeline_event_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ALTER COLUMN "document_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_3d4f8001664e4a32d09ae6096da" FOREIGN KEY ("sender_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_cd7b226c0eea663dd9b2d12917a" FOREIGN KEY ("timeline_event_id") REFERENCES "edm_document_timeline_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_a073b7c4420bd01bbd3c1cb5b7f" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ALTER COLUMN "task_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ALTER COLUMN "document_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_56724b2f6e7a29d26a76752de90" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_0eb30ac5f71609857a202455c05" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" ALTER COLUMN "template_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" ADD CONSTRAINT "FK_3ce49798d851e7a8368881d2361" FOREIGN KEY ("template_id") REFERENCES "edm_document_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ALTER COLUMN "actor_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ALTER COLUMN "document_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_af2ff1dc4188f1dc0f122a2ca37" FOREIGN KEY ("actor_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_6208dbc3cbbe81c855d0abd402f" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ALTER COLUMN "document_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "UQ_EDM_REG_JOURNAL_NUMBER" UNIQUE ("registration_number")`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ALTER COLUMN "template_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_fdddb7bf3ded6561a76f8d96a2a" FOREIGN KEY ("template_id") REFERENCES "edm_route_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" ADD CONSTRAINT "FK_05caf390cbd40baffad56a576a8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ALTER COLUMN "actor_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ALTER COLUMN "document_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ALTER COLUMN "stage_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_a66554a9bcd873cfc3b8ccbb06b" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_4b15bfe33b4bdc4863e7484b98a" FOREIGN KEY ("stage_id") REFERENCES "edm_route_stages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ALTER COLUMN "route_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_315b745a0b22dbc26cdb33ea596" FOREIGN KEY ("route_id") REFERENCES "edm_document_routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ALTER COLUMN "document_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "FK_83e4e52bfe54b62e2fec2844563" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ALTER COLUMN "department_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ALTER COLUMN "delegate_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ALTER COLUMN "delegator_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "file_access_audit" ALTER COLUMN "file_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "file_access_audit" ADD CONSTRAINT "FK_d363482d039e3b7e5ab863c5d9e" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_links" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "file_links" ALTER COLUMN "file_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "file_links" ADD CONSTRAINT "FK_64db2f1947f0f95e79d8659207f" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "owner_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "receiver_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "status" character varying NOT NULL DEFAULT 'new'`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD "path" ltree NOT NULL`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "calls"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" ADD CONSTRAINT "UQ_EDM_REGISTRY_SCOPE" UNIQUE ("department_id", "doc_type", "year")`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "UQ_EDM_DOCUMENT_TASK_LINK" UNIQUE ("document_id", "task_id")`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" ADD CONSTRAINT "UQ_EDM_DOCUMENT_TEMPLATE_FIELD" UNIQUE ("template_id", "field_key")`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "UQ_EDM_ROUTE_DOCUMENT_VERSION" UNIQUE ("document_id", "version_no")`);
        await queryRunner.query(`ALTER TABLE "file_links" ADD CONSTRAINT "UQ_FILE_LINK_RESOURCE" UNIQUE ("file_id", "resource_type", "resource_id")`);
        await queryRunner.query(`ALTER TABLE "iam_business_roles" ADD CONSTRAINT "CHK_IAM_BUSINESS_ROLES_DEFAULT_SCOPE" CHECK (((default_scope)::text = ANY ((ARRAY['self'::character varying, 'department'::character varying, 'subtree'::character varying, 'global'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "CHK_EDM_ALERT_STATUS" CHECK (((status)::text = ANY ((ARRAY['unread'::character varying, 'read'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "CHK_EDM_ALERT_KIND" CHECK (((kind)::text = ANY ((ARRAY['due_soon'::character varying, 'overdue'::character varying, 'escalation'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "CHK_EDM_DOCUMENT_TEMPLATE_SCOPE_TYPE" CHECK (((scope_type)::text = ANY ((ARRAY['department'::character varying, 'global'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "CHK_EDM_DOCUMENT_TEMPLATE_DOC_TYPE" CHECK (((document_type)::text = ANY ((ARRAY['incoming'::character varying, 'outgoing'::character varying, 'internal'::character varying, 'order'::character varying, 'resolution'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" ADD CONSTRAINT "CHK_EDM_DOCUMENT_TEMPLATE_FIELD_KEY" CHECK (((field_key)::text = ANY ((ARRAY['title'::character varying, 'subject'::character varying, 'summary'::character varying, 'resolutionText'::character varying, 'dueAt'::character varying, 'confidentiality'::character varying, 'type'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "CHK_EDM_TIMELINE_EVENT_TYPE" CHECK (((event_type)::text = ANY ((ARRAY['created'::character varying, 'forwarded'::character varying, 'responsible_assigned'::character varying, 'responsible_reassigned'::character varying, 'reply_sent'::character varying, 'route_action'::character varying, 'override'::character varying, 'archived'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "CHK_EDM_REG_JOURNAL_STATUS" CHECK (((status)::text = ANY ((ARRAY['registered'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "CHK_EDM_REG_JOURNAL_TYPE" CHECK (((journal_type)::text = ANY ((ARRAY['incoming'::character varying, 'outgoing'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_SCOPE_TYPE" CHECK (((scope_type)::text = ANY ((ARRAY['department'::character varying, 'global'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_ASSIGNEE_CONSISTENCY" CHECK (((((assignee_type)::text = 'user'::text) AND (assignee_user_id IS NOT NULL)) OR (((assignee_type)::text = 'role'::text) AND (assignee_role IS NOT NULL)) OR ((assignee_type)::text = 'department_head'::text)))`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_ASSIGNEE_TYPE" CHECK (((assignee_type)::text = ANY ((ARRAY['user'::character varying, 'role'::character varying, 'department_head'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "CHK_EDM_ROUTE_TEMPLATE_STAGE_TYPE" CHECK (((stage_type)::text = ANY ((ARRAY['review'::character varying, 'sign'::character varying, 'approve'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" ADD CONSTRAINT "CHK_EDM_SAVED_FILTER_SCOPE" CHECK (((scope)::text = 'documents'::text))`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "CHK_EDM_ACTION_RESULT_STATE" CHECK (((action_result_state)::text = ANY ((ARRAY['approved'::character varying, 'rejected'::character varying, 'returned'::character varying, 'commented'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "CHK_EDM_ACTION" CHECK (((action)::text = ANY ((ARRAY['approved'::character varying, 'rejected'::character varying, 'returned_for_revision'::character varying, 'commented'::character varying, 'override_approved'::character varying, 'override_rejected'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "CHK_EDM_ASSIGNEE_CONSISTENCY" CHECK (((((assignee_type)::text = 'user'::text) AND (assignee_user_id IS NOT NULL)) OR (((assignee_type)::text = 'role'::text) AND (assignee_role IS NOT NULL)) OR (((assignee_type)::text = 'department_head'::text) AND (assignee_department_id IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "CHK_EDM_STAGE_STATE" CHECK (((state)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying, 'approved'::character varying, 'rejected'::character varying, 'returned'::character varying, 'skipped'::character varying, 'expired'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "CHK_EDM_ASSIGNEE_TYPE" CHECK (((assignee_type)::text = ANY ((ARRAY['user'::character varying, 'role'::character varying, 'department_head'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "CHK_EDM_STAGE_TYPE" CHECK (((stage_type)::text = ANY ((ARRAY['review'::character varying, 'sign'::character varying, 'approve'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "CHK_EDM_ROUTE_COMPLETION_POLICY" CHECK (((completion_policy)::text = ANY ((ARRAY['sequential'::character varying, 'parallel_all_of'::character varying, 'parallel_any_of'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "CHK_EDM_ROUTE_STATE" CHECK (((state)::text = ANY ((ARRAY['active'::character varying, 'completed'::character varying, 'rejected'::character varying, 'returned'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "CHK_EDM_DOCUMENT_CONFIDENTIALITY" CHECK (((confidentiality)::text = ANY ((ARRAY['public_internal'::character varying, 'department_confidential'::character varying, 'restricted'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "CHK_EDM_DOCUMENT_TYPE" CHECK (((type)::text = ANY ((ARRAY['incoming'::character varying, 'outgoing'::character varying, 'internal'::character varying, 'order'::character varying, 'resolution'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "CHK_EDM_DOCUMENT_STATUS" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'in_route'::character varying, 'approved'::character varying, 'rejected'::character varying, 'returned_for_revision'::character varying, 'archived'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "CHK_IAM_DELEGATIONS_DISTINCT_USERS" CHECK ((delegator_user_id <> delegate_user_id))`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "CHK_IAM_DELEGATIONS_VALID_RANGE" CHECK ((valid_from < valid_to))`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "CHK_IAM_DELEGATIONS_STATUS" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'revoked'::character varying, 'expired'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "CHK_IAM_DELEGATIONS_SCOPE_TYPE" CHECK (((scope_type)::text = ANY ((ARRAY['department'::character varying, 'global'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD CONSTRAINT "CHK_ORG_UNITS_TYPE" CHECK (((type)::text = ANY ((ARRAY['committee'::character varying, 'department'::character varying, 'division'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "IDX_DISASTERS_CREATED_AT" ON "disasters" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_DISASTERS_DEPARTMENT_ID" ON "disasters" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DISASTERS_SEVERITY" ON "disasters" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_DISASTERS_STATUS" ON "disasters" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_DISASTER_TYPES_CATEGORY_ID" ON "disaster_types" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_AUDIT_USER_CREATED_AT" ON "auth_audit_logs" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_AUDIT_LOGS_CREATED_AT" ON "auth_audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_AUDIT_LOGS_ACTION" ON "auth_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_AUDIT_LOGS_USER_ID" ON "auth_audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENTS_RECEIVER_ID" ON "documents" ("receiver_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENTS_SENDER_ID" ON "documents" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENTS_CREATED_AT" ON "documents" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENTS_DEPARTMENT_ID" ON "documents" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENTS_STATUS" ON "documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENTS_TYPE" ON "documents" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ALERT_RECIPIENT_KIND_STATUS_CREATED" ON "edm_alerts" ("created_at", "kind", "recipient_user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ALERT_RECIPIENT_CREATED_AT" ON "edm_alerts" ("created_at", "recipient_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ALERT_CREATED_AT" ON "edm_alerts" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ALERT_STAGE_KIND" ON "edm_alerts" ("kind", "stage_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ALERT_RECIPIENT_STATUS" ON "edm_alerts" ("recipient_user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_EDM_REGISTRY_SCOPE" ON "edm_document_registry_sequences" ("department_id", "doc_type", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_REPLY_THREAD_CREATED_AT" ON "edm_document_replies" ("created_at", "thread_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_REPLY_DOCUMENT_CREATED_AT" ON "edm_document_replies" ("created_at", "document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_TASK_LINK_TASK" ON "edm_document_task_links" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_TASK_LINK_DOCUMENT" ON "edm_document_task_links" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOCUMENT_TEMPLATE_ACTIVE_UPDATED_AT" ON "edm_document_templates" ("is_active", "updated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOCUMENT_TEMPLATE_DEPARTMENT_ACTIVE" ON "edm_document_templates" ("department_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOCUMENT_TEMPLATE_SCOPE_ACTIVE" ON "edm_document_templates" ("is_active", "scope_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOCUMENT_TEMPLATE_FIELD_SORT" ON "edm_document_template_fields" ("sort_order", "template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOCUMENT_TEMPLATE_FIELD_TEMPLATE" ON "edm_document_template_fields" ("template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_TIMELINE_EVENT_TYPE_CREATED_AT" ON "edm_document_timeline_events" ("created_at", "event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_TIMELINE_THREAD_CREATED_AT" ON "edm_document_timeline_events" ("created_at", "thread_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_TIMELINE_DOCUMENT_CREATED_AT" ON "edm_document_timeline_events" ("created_at", "document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_REG_JOURNAL_TYPE_STATUS_REGISTERED_AT" ON "edm_registration_journal" ("journal_type", "registered_at", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_REG_JOURNAL_REGISTERED_AT" ON "edm_registration_journal" ("registered_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_REG_JOURNAL_TYPE_STATUS" ON "edm_registration_journal" ("journal_type", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_TEMPLATE_ACTIVE_UPDATED_AT" ON "edm_route_templates" ("is_active", "updated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_TEMPLATE_DEPARTMENT_ACTIVE" ON "edm_route_templates" ("department_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_TEMPLATE_SCOPE_ACTIVE" ON "edm_route_templates" ("is_active", "scope_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_TEMPLATE_STAGE_TEMPLATE_ORDER" ON "edm_route_template_stages" ("order_no", "template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_SAVED_FILTER_USER_NAME" ON "edm_saved_filters" ("name", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_SAVED_FILTER_USER_DEFAULT" ON "edm_saved_filters" ("is_default", "scope", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_SAVED_FILTER_USER_SCOPE" ON "edm_saved_filters" ("scope", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ACTION_ACTOR_CREATED_AT" ON "edm_stage_actions" ("actor_user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ACTION_DOCUMENT_CREATED_AT" ON "edm_stage_actions" ("created_at", "document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ACTION_STAGE_CREATED_AT" ON "edm_stage_actions" ("created_at", "stage_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_STAGE_ASSIGNEE_DEPT_STATE_DUE_AT" ON "edm_route_stages" ("assignee_department_id", "assignee_type", "due_at", "state") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_STAGE_ASSIGNEE_USER_STATE_DUE_AT" ON "edm_route_stages" ("assignee_user_id", "due_at", "state") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_STAGE_STATE_DUE_AT" ON "edm_route_stages" ("due_at", "state") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_STAGE_ASSIGNEE_USER_STATE" ON "edm_route_stages" ("assignee_user_id", "state") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_STAGE_ROUTE_STATE" ON "edm_route_stages" ("route_id", "state") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_STAGE_ROUTE_ORDER" ON "edm_route_stages" ("order_no", "route_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_DOCUMENT_VERSION" ON "edm_document_routes" ("document_id", "version_no") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_CREATED_AT" ON "edm_document_routes" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_STATE_CREATED_AT" ON "edm_document_routes" ("created_at", "state") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_ROUTE_DOCUMENT_ID" ON "edm_document_routes" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_edm_documents_document_kind" ON "edm_documents" ("document_kind_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_CURRENT_ROUTE_ID" ON "edm_documents" ("current_route_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_TYPE_STATUS_CREATED_AT" ON "edm_documents" ("created_at", "status", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_DEPT_STATUS_CREATED_AT" ON "edm_documents" ("created_at", "department_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_DELETED_CREATED_AT" ON "edm_documents" ("created_at", "deleted_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_EDM_DOC_EXTERNAL_NUMBER" ON "edm_documents" ("external_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_CREATOR_CREATED_AT" ON "edm_documents" ("created_at", "creator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_DEPARTMENT_STATUS" ON "edm_documents" ("department_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_EDM_DOC_STATUS_CREATED_AT" ON "edm_documents" ("created_at", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_DELEGATION_SCOPE_ORG_UNIT" ON "iam_delegations" ("scope_org_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DELEGATION_DELEGATOR_VALIDITY" ON "iam_delegations" ("delegator_user_id", "status", "valid_from", "valid_to") `);
        await queryRunner.query(`CREATE INDEX "IDX_DELEGATION_DELEGATE_VALIDITY" ON "iam_delegations" ("delegate_user_id", "status", "valid_from", "valid_to") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_ACCESS_AUDIT_FILE_CREATED_AT" ON "file_access_audit" ("created_at", "file_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_ACCESS_AUDIT_USER_CREATED_AT" ON "file_access_audit" ("actor_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_ACCESS_AUDIT_CREATED_AT" ON "file_access_audit" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_ACCESS_AUDIT_ACTION" ON "file_access_audit" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_ACCESS_AUDIT_ACTOR_ID" ON "file_access_audit" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_ACCESS_AUDIT_FILE_ID" ON "file_access_audit" ("file_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_LINKS_RESOURCE" ON "file_links" ("resource_id", "resource_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILE_LINKS_FILE_ID" ON "file_links" ("file_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_DEPT_STATUS_CREATED_AT" ON "files" ("created_at", "department_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_OWNER_STATUS_CREATED_AT" ON "files" ("created_at", "owner_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_STATUS" ON "files" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_DEPARTMENT_ID" ON "files" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_OWNER_ID" ON "files" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIS_FEATURES_LAYER_STATUS" ON "gis_features" ("layer_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIS_FEATURES_CREATED_AT" ON "gis_features" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIS_FEATURES_LAT_LNG" ON "gis_features" ("latitude", "longitude") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIS_FEATURES_DEPT_STATUS" ON "gis_features" ("department_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIS_FEATURES_STATUS_SEVERITY" ON "gis_features" ("severity", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIS_LAYERS_TYPE" ON "gis_layers" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIS_LAYERS_DEPT_ACTIVE" ON "gis_layers" ("department_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_CREATOR_STATUS_CREATED_AT" ON "tasks" ("created_at", "creator_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_RECEIVER_STATUS_CREATED_AT" ON "tasks" ("created_at", "receiver_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_CREATED_AT" ON "tasks" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_RECEIVER_ID" ON "tasks" ("receiver_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_CREATOR_ID" ON "tasks" ("creator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_STATUS" ON "tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_BULK_IMPORT_OPS_TYPE" ON "bulk_import_operations" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_BULK_IMPORT_OPS_ACTOR_ID" ON "bulk_import_operations" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BULK_IMPORT_OPS_CREATED_AT" ON "bulk_import_operations" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_CHANGE_AUDIT_TARGET_CREATED_AT" ON "user_change_audit_logs" ("created_at", "target_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_CHANGE_AUDIT_CREATED_AT" ON "user_change_audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_CHANGE_AUDIT_ACTION" ON "user_change_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_CHANGE_AUDIT_TARGET_USER_ID" ON "user_change_audit_logs" ("target_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_CHANGE_AUDIT_ACTOR_ID" ON "user_change_audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_DEPT_ROLE_ACTIVE" ON "user" ("department_id", "isActive", "role") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_DEPT_ACTIVE_CREATED_AT" ON "user" ("created_at", "department_id", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_ORG_UNIT_ID" ON "user" ("org_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_BUSINESS_ROLE" ON "user" ("business_role") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_CREATED_AT" ON "user" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_IS_ACTIVE" ON "user" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_ROLE" ON "user" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_DEPARTMENT_ID" ON "user" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORG_UNITS_PATH_GIST" ON "org_units" USING GiST ("path") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORG_UNITS_TYPE" ON "org_units" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORG_UNITS_PARENT_ID" ON "org_units" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DEPARTMENTS_TYPE" ON "departments" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_DEPARTMENTS_PARENT_ID" ON "departments" ("parent_id") `);
        await queryRunner.query(`ALTER TABLE "disasters" ADD CONSTRAINT "FK_178367b82fb965637d69222189e" FOREIGN KEY ("type_id") REFERENCES "disaster_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disasters" ADD CONSTRAINT "FK_c7a8da7d338b26a90d37eb45fa5" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" ADD CONSTRAINT "FK_24ac4f04dd37d321ee7f50b8b96" FOREIGN KEY ("actor_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" ADD CONSTRAINT "FK_c7cfc526890ae8386b480349120" FOREIGN KEY ("on_behalf_of_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_22152d6ddc87213d39d48cf02d4" FOREIGN KEY ("sender_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_2084e87705a9e82da5b6155b34b" FOREIGN KEY ("receiver_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_24a226d1434cd9a9748d5f11959" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" ADD CONSTRAINT "FK_1dd9e424c2049d801226d7b093d" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_b84c416889d4b932181651fcfe7" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_0e52f75963f6396469f374fc62a" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_a0683e3c4d5d9c260c23670b407" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_fc2b6c8fb9bb600ea350834d921" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_0b3ae928b45b6b2689ed7d6c074" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_8b633284d47de67800345e8dfba" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_00e35de7efa8506d0594dad3a99" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_bdaabe55e703ab72a6166ccc2e2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_cb9eaa5a2ad3500d56acd4e1788" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_bb080db9f06e15e64aae9eb3a20" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_55c90edc007fd99b0bc0e99939a" FOREIGN KEY ("assignee_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_d62a0d61aa4521efb406d53b2c9" FOREIGN KEY ("assignee_department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_fd49bbbbbc0f857cb04b54af529" FOREIGN KEY ("actor_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_d4cfe44c70962730c5e6a4f874d" FOREIGN KEY ("on_behalf_of_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_0f6a636b1197bde1cbf3ad7e0cd" FOREIGN KEY ("assignee_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_fba02ee9095f83950220f0731cf" FOREIGN KEY ("assignee_department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "FK_b1f120110cbed36432933d387d4" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_e40e6c1adb9151892020545d241" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_b8bf993005538aed05a0903c182" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_deed290f1b3b94f901d321a6781" FOREIGN KEY ("current_route_id") REFERENCES "edm_document_routes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_edm_documents_document_kind" FOREIGN KEY ("document_kind_id") REFERENCES "edm_document_kinds"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" ADD CONSTRAINT "FK_edm_document_kinds_created_by" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" ADD CONSTRAINT "FK_edm_document_kinds_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_8946ca43f41b4fcbc725a7f8d1c" FOREIGN KEY ("delegator_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_9030ba74cb54f3c65fcf309570f" FOREIGN KEY ("delegate_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_1d312a094ffbc86e70c8893854d" FOREIGN KEY ("scope_department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_2c2540c0d341c8e20048681f4c3" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_707a5642f0c835dbc89e603cbd5" FOREIGN KEY ("scope_org_unit_id") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_links" ADD CONSTRAINT "FK_c78a61293671a996c88094cc56f" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_4bc1db1f4f34ec9415acd88afdb" FOREIGN KEY ("owner_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_fe49ddbcf2436d7a6fbbbc71293" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_f4cb489461bc751498a28852356" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_ed83132cc853103ac2acd948992" FOREIGN KEY ("receiver_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_afd2c87bee70dd5557f48911e66" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_9d207f670875c015e66e25bfe0b" FOREIGN KEY ("org_unit_id") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_9be04828b2f746bc83268766626" FOREIGN KEY ("business_role") REFERENCES "iam_business_roles"("code") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD CONSTRAINT "FK_93e336d1c079edb2cecd9c8f599" FOREIGN KEY ("parent_id") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b" FOREIGN KEY ("parent_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_372ba8832ed6f97bccd2d696cbd" FOREIGN KEY ("chief_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
