import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1771787796414 implements MigrationInterface {
    name = 'AutoMigration1771787796414'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "org_units" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "path" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "parent_id" integer, CONSTRAINT "PK_b4a19b7f3756560cd75643be5a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bulk_import_operations" ("id" SERIAL NOT NULL, "operation_id" character varying NOT NULL, "session_id" character varying, "type" character varying NOT NULL, "status" character varying NOT NULL, "mode" character varying, "idempotency_key" character varying, "total_rows" integer, "valid_rows" integer, "invalid_rows" integer, "created_count" integer, "updated_count" integer, "skipped_count" integer, "failed_count" integer, "warnings_count" integer, "errors_count" integer, "details" json, "ip" character varying, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "actor_id" integer, CONSTRAINT "UQ_4ed6ddffed524862fa448a08fe4" UNIQUE ("operation_id"), CONSTRAINT "PK_463fdd984d9335d379a5e9a07fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."gis_layers_type_enum" AS ENUM('incident', 'zone', 'resource', 'route', 'checkpoint')`);
        await queryRunner.query(`CREATE TABLE "gis_layers" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "type" "public"."gis_layers_type_enum" NOT NULL DEFAULT 'incident', "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "department_id" integer, "created_by" integer, CONSTRAINT "PK_1e06683809bc101c38d18d66f84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."gis_features_severity_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."gis_features_status_enum" AS ENUM('active', 'resolved', 'monitoring', 'archived')`);
        await queryRunner.query(`CREATE TABLE "gis_features" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "geometry" jsonb, "severity" "public"."gis_features_severity_enum" NOT NULL DEFAULT 'medium', "status" "public"."gis_features_status_enum" NOT NULL DEFAULT 'active', "properties" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "layer_id" integer, "department_id" integer, "created_by" integer, CONSTRAINT "PK_14de122884df821a2a068a35b84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "iam_delegations" ("id" SERIAL NOT NULL, "scope_type" character varying NOT NULL, "scope_org_unit_id" integer, "permission_subset" jsonb NOT NULL, "valid_from" TIMESTAMP NOT NULL, "valid_to" TIMESTAMP NOT NULL, "status" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "delegator_user_id" integer, "delegate_user_id" integer, "scope_department_id" integer, "created_by" integer, CONSTRAINT "PK_ce5b479270c6ad17760cb350cee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_kinds" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by_id" integer, "updated_by_id" integer, CONSTRAINT "UQ_d694395c68fa23ff856a90a1978" UNIQUE ("code"), CONSTRAINT "PK_f07e2290822b938c8af5f97163b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_documents" ("id" SERIAL NOT NULL, "external_number" character varying, "type" character varying NOT NULL, "status" character varying NOT NULL, "title" character varying NOT NULL, "subject" text, "summary" text, "resolution_text" text, "confidentiality" character varying NOT NULL DEFAULT 'public_internal', "due_at" TIMESTAMP, "approved_at" TIMESTAMP, "rejected_at" TIMESTAMP, "archived_at" TIMESTAMP, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "department_id" integer, "creator_id" integer, "document_kind_id" integer, "current_route_id" integer, CONSTRAINT "PK_af0258c85b7fa2b438a61009832" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_routes" ("id" SERIAL NOT NULL, "version_no" integer NOT NULL, "state" character varying NOT NULL, "completion_policy" character varying NOT NULL DEFAULT 'sequential', "started_at" TIMESTAMP, "finished_at" TIMESTAMP, "override_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "document_id" integer, "created_by" integer, CONSTRAINT "PK_d3ac996c3e9ddbdcb9612a79f42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_route_stages" ("id" SERIAL NOT NULL, "order_no" integer NOT NULL, "stage_group_no" integer, "stage_type" character varying NOT NULL, "assignee_type" character varying NOT NULL, "assignee_role" character varying, "state" character varying NOT NULL DEFAULT 'pending', "due_at" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "escalation_policy" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "route_id" integer, "assignee_user_id" integer, "assignee_department_id" integer, CONSTRAINT "PK_239b46503bee32ab718b6f868dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_stage_actions" ("id" SERIAL NOT NULL, "action" character varying NOT NULL, "action_result_state" character varying NOT NULL, "comment_text" text, "reason_code" character varying, "ip" character varying, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "stage_id" integer, "document_id" integer, "actor_user_id" integer, "on_behalf_of_user_id" integer, CONSTRAINT "PK_efa6b0aed7ca7decf0853b4a125" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_saved_filters" ("id" SERIAL NOT NULL, "scope" character varying NOT NULL DEFAULT 'documents', "name" character varying NOT NULL, "criteria" jsonb NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_058ae2a39ce31f5cc47a231e3d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_route_template_stages" ("id" SERIAL NOT NULL, "order_no" integer NOT NULL, "stage_group_no" integer, "stage_type" character varying NOT NULL, "assignee_type" character varying NOT NULL, "assignee_role" character varying, "due_in_hours" integer, "escalation_policy" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "template_id" integer, "assignee_user_id" integer, "assignee_department_id" integer, CONSTRAINT "PK_13fb9248bc2bc0327a42da24ad5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_route_templates" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "scope_type" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "department_id" integer, "created_by" integer, "updated_by" integer, CONSTRAINT "PK_636b6db6416792ce86d1675015a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_registration_journal" ("id" SERIAL NOT NULL, "journal_type" character varying NOT NULL, "registration_number" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'registered', "registered_at" TIMESTAMP NOT NULL, "cancelled_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "document_id" integer, "created_by" integer, "updated_by" integer, CONSTRAINT "REL_0b3ae928b45b6b2689ed7d6c07" UNIQUE ("document_id"), CONSTRAINT "PK_a00009850768cad581dd4afb409" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_templates" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "document_type" character varying NOT NULL, "scope_type" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "department_id" integer, "created_by" integer, "updated_by" integer, CONSTRAINT "PK_f8bff8d146e57da5ded4eb8f9d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_template_fields" ("id" SERIAL NOT NULL, "field_key" character varying NOT NULL, "label" character varying NOT NULL, "field_type" character varying NOT NULL DEFAULT 'text', "is_required" boolean NOT NULL DEFAULT false, "is_readonly" boolean NOT NULL DEFAULT false, "default_value" text, "sort_order" integer NOT NULL DEFAULT '100', "validation_rules" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "template_id" integer, CONSTRAINT "PK_a30a9d8747129637d03c4aedd0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_timeline_events" ("id" SERIAL NOT NULL, "event_type" character varying NOT NULL, "from_role" character varying, "to_role" character varying, "thread_id" character varying, "comment_text" text, "meta" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "document_id" integer, "actor_user_id" integer, "from_user_id" integer, "to_user_id" integer, "responsible_user_id" integer, "parent_event_id" integer, CONSTRAINT "PK_4970beed67230f0d88a7a1dce19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_task_links" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "document_id" integer, "task_id" integer, "created_by" integer, CONSTRAINT "PK_f71187c6976838c0c8f24d5fbed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_registry_sequences" ("id" SERIAL NOT NULL, "doc_type" character varying NOT NULL, "year" integer NOT NULL, "last_value" integer NOT NULL DEFAULT '0', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "department_id" integer, CONSTRAINT "PK_d6bc0ea836fab9a746f420a8e5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_document_replies" ("id" SERIAL NOT NULL, "thread_id" character varying NOT NULL, "message_text" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "document_id" integer, "timeline_event_id" integer, "sender_user_id" integer, "parent_reply_id" integer, CONSTRAINT "PK_ad5a18827527929c7b9e5296b50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "edm_alerts" ("id" SERIAL NOT NULL, "kind" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'unread', "message" text NOT NULL, "metadata" jsonb, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "document_id" integer, "stage_id" integer, "recipient_user_id" integer, CONSTRAINT "PK_48fabf98de5102f59ada29e8ca4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permission_profiles" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "permissions" jsonb NOT NULL DEFAULT '[]', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_PERMISSION_PROFILES_CODE" UNIQUE ("code"), CONSTRAINT "PK_acfec88b8a379c559a532734534" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "iam_business_roles" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "default_scope" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_IAM_BUSINESS_ROLES_CODE" UNIQUE ("code"), CONSTRAINT "PK_78df9d090c3768134a0ad234dc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_role_permission_profiles" ("id" SERIAL NOT NULL, "priority" integer NOT NULL DEFAULT '100', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "business_role_id" integer, "permission_profile_id" integer, CONSTRAINT "UQ_BUSINESS_ROLE_PERMISSION_PROFILE_PAIR" UNIQUE ("business_role_id", "permission_profile_id"), CONSTRAINT "PK_6b5ac6e25984c19982ff8780e98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user" ADD "business_role" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD "org_unit_id" integer`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" ADD "actor_user_id" integer`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" ADD "on_behalf_of_user_id" integer`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD CONSTRAINT "FK_93e336d1c079edb2cecd9c8f599" FOREIGN KEY ("parent_id") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_9d207f670875c015e66e25bfe0b" FOREIGN KEY ("org_unit_id") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bulk_import_operations" ADD CONSTRAINT "FK_85c062412f52428eb4ac1415b46" FOREIGN KEY ("actor_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gis_layers" ADD CONSTRAINT "FK_1f5043e3a28bb9e7ef52db78ba7" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gis_layers" ADD CONSTRAINT "FK_c89661cb27502cbddbf498652dd" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gis_features" ADD CONSTRAINT "FK_5268fa7dbaf156831ed517f3759" FOREIGN KEY ("layer_id") REFERENCES "gis_layers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gis_features" ADD CONSTRAINT "FK_90483a9d81a0cbed09b25f6deef" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gis_features" ADD CONSTRAINT "FK_48ba677bd3fd44b3a6691a8c2d8" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_8946ca43f41b4fcbc725a7f8d1c" FOREIGN KEY ("delegator_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_9030ba74cb54f3c65fcf309570f" FOREIGN KEY ("delegate_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_1d312a094ffbc86e70c8893854d" FOREIGN KEY ("scope_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_707a5642f0c835dbc89e603cbd5" FOREIGN KEY ("scope_org_unit_id") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" ADD CONSTRAINT "FK_2c2540c0d341c8e20048681f4c3" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" ADD CONSTRAINT "FK_904360fe69c9f60910fb7cef217" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" ADD CONSTRAINT "FK_3bcd0bf9b7cb046ce5d71b057a6" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_e40e6c1adb9151892020545d241" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_b8bf993005538aed05a0903c182" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_6d875d41ecb59952cf306d1228d" FOREIGN KEY ("document_kind_id") REFERENCES "edm_document_kinds"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_documents" ADD CONSTRAINT "FK_deed290f1b3b94f901d321a6781" FOREIGN KEY ("current_route_id") REFERENCES "edm_document_routes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "FK_83e4e52bfe54b62e2fec2844563" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" ADD CONSTRAINT "FK_b1f120110cbed36432933d387d4" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_315b745a0b22dbc26cdb33ea596" FOREIGN KEY ("route_id") REFERENCES "edm_document_routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_0f6a636b1197bde1cbf3ad7e0cd" FOREIGN KEY ("assignee_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" ADD CONSTRAINT "FK_fba02ee9095f83950220f0731cf" FOREIGN KEY ("assignee_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_4b15bfe33b4bdc4863e7484b98a" FOREIGN KEY ("stage_id") REFERENCES "edm_route_stages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_a66554a9bcd873cfc3b8ccbb06b" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_fd49bbbbbc0f857cb04b54af529" FOREIGN KEY ("actor_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" ADD CONSTRAINT "FK_d4cfe44c70962730c5e6a4f874d" FOREIGN KEY ("on_behalf_of_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" ADD CONSTRAINT "FK_05caf390cbd40baffad56a576a8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_fdddb7bf3ded6561a76f8d96a2a" FOREIGN KEY ("template_id") REFERENCES "edm_route_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_55c90edc007fd99b0bc0e99939a" FOREIGN KEY ("assignee_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" ADD CONSTRAINT "FK_d62a0d61aa4521efb406d53b2c9" FOREIGN KEY ("assignee_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_bdaabe55e703ab72a6166ccc2e2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_cb9eaa5a2ad3500d56acd4e1788" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" ADD CONSTRAINT "FK_bb080db9f06e15e64aae9eb3a20" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_0b3ae928b45b6b2689ed7d6c074" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_8b633284d47de67800345e8dfba" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" ADD CONSTRAINT "FK_00e35de7efa8506d0594dad3a99" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_0e52f75963f6396469f374fc62a" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_a0683e3c4d5d9c260c23670b407" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" ADD CONSTRAINT "FK_fc2b6c8fb9bb600ea350834d921" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" ADD CONSTRAINT "FK_3ce49798d851e7a8368881d2361" FOREIGN KEY ("template_id") REFERENCES "edm_document_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_6208dbc3cbbe81c855d0abd402f" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_af2ff1dc4188f1dc0f122a2ca37" FOREIGN KEY ("actor_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_8bb15341b30c7353802e41d0340" FOREIGN KEY ("from_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_6841b136c377da14febb631b958" FOREIGN KEY ("to_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_009dd7a2dc7b21a7df30b48ece5" FOREIGN KEY ("responsible_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" ADD CONSTRAINT "FK_fc45dd35ce1723e3161bde5e957" FOREIGN KEY ("parent_event_id") REFERENCES "edm_document_timeline_events"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_0eb30ac5f71609857a202455c05" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_56724b2f6e7a29d26a76752de90" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" ADD CONSTRAINT "FK_b84c416889d4b932181651fcfe7" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" ADD CONSTRAINT "FK_1dd9e424c2049d801226d7b093d" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_a073b7c4420bd01bbd3c1cb5b7f" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_cd7b226c0eea663dd9b2d12917a" FOREIGN KEY ("timeline_event_id") REFERENCES "edm_document_timeline_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_3d4f8001664e4a32d09ae6096da" FOREIGN KEY ("sender_user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" ADD CONSTRAINT "FK_2f349f5e965e65cb4eb53c408cd" FOREIGN KEY ("parent_reply_id") REFERENCES "edm_document_replies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_eda2a65b0f125f7c6ae0b7b6039" FOREIGN KEY ("document_id") REFERENCES "edm_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_c3dfcf1e88da3a9ad63c41809b0" FOREIGN KEY ("stage_id") REFERENCES "edm_route_stages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" ADD CONSTRAINT "FK_dc16f5fd345854683468625bad9" FOREIGN KEY ("recipient_user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "FK_1bbe5812d6dadf6a5e18602c1c3" FOREIGN KEY ("business_role_id") REFERENCES "iam_business_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" ADD CONSTRAINT "FK_2aec8289d19d36055fb99f98cf9" FOREIGN KEY ("permission_profile_id") REFERENCES "permission_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "FK_2aec8289d19d36055fb99f98cf9"`);
        await queryRunner.query(`ALTER TABLE "business_role_permission_profiles" DROP CONSTRAINT "FK_1bbe5812d6dadf6a5e18602c1c3"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_dc16f5fd345854683468625bad9"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_c3dfcf1e88da3a9ad63c41809b0"`);
        await queryRunner.query(`ALTER TABLE "edm_alerts" DROP CONSTRAINT "FK_eda2a65b0f125f7c6ae0b7b6039"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_2f349f5e965e65cb4eb53c408cd"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_3d4f8001664e4a32d09ae6096da"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_cd7b226c0eea663dd9b2d12917a"`);
        await queryRunner.query(`ALTER TABLE "edm_document_replies" DROP CONSTRAINT "FK_a073b7c4420bd01bbd3c1cb5b7f"`);
        await queryRunner.query(`ALTER TABLE "edm_document_registry_sequences" DROP CONSTRAINT "FK_1dd9e424c2049d801226d7b093d"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_b84c416889d4b932181651fcfe7"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_56724b2f6e7a29d26a76752de90"`);
        await queryRunner.query(`ALTER TABLE "edm_document_task_links" DROP CONSTRAINT "FK_0eb30ac5f71609857a202455c05"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_fc45dd35ce1723e3161bde5e957"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_009dd7a2dc7b21a7df30b48ece5"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_6841b136c377da14febb631b958"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_8bb15341b30c7353802e41d0340"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_af2ff1dc4188f1dc0f122a2ca37"`);
        await queryRunner.query(`ALTER TABLE "edm_document_timeline_events" DROP CONSTRAINT "FK_6208dbc3cbbe81c855d0abd402f"`);
        await queryRunner.query(`ALTER TABLE "edm_document_template_fields" DROP CONSTRAINT "FK_3ce49798d851e7a8368881d2361"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_fc2b6c8fb9bb600ea350834d921"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_a0683e3c4d5d9c260c23670b407"`);
        await queryRunner.query(`ALTER TABLE "edm_document_templates" DROP CONSTRAINT "FK_0e52f75963f6396469f374fc62a"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_00e35de7efa8506d0594dad3a99"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_8b633284d47de67800345e8dfba"`);
        await queryRunner.query(`ALTER TABLE "edm_registration_journal" DROP CONSTRAINT "FK_0b3ae928b45b6b2689ed7d6c074"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_bb080db9f06e15e64aae9eb3a20"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_cb9eaa5a2ad3500d56acd4e1788"`);
        await queryRunner.query(`ALTER TABLE "edm_route_templates" DROP CONSTRAINT "FK_bdaabe55e703ab72a6166ccc2e2"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_d62a0d61aa4521efb406d53b2c9"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_55c90edc007fd99b0bc0e99939a"`);
        await queryRunner.query(`ALTER TABLE "edm_route_template_stages" DROP CONSTRAINT "FK_fdddb7bf3ded6561a76f8d96a2a"`);
        await queryRunner.query(`ALTER TABLE "edm_saved_filters" DROP CONSTRAINT "FK_05caf390cbd40baffad56a576a8"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_d4cfe44c70962730c5e6a4f874d"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_fd49bbbbbc0f857cb04b54af529"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_a66554a9bcd873cfc3b8ccbb06b"`);
        await queryRunner.query(`ALTER TABLE "edm_stage_actions" DROP CONSTRAINT "FK_4b15bfe33b4bdc4863e7484b98a"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_fba02ee9095f83950220f0731cf"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_0f6a636b1197bde1cbf3ad7e0cd"`);
        await queryRunner.query(`ALTER TABLE "edm_route_stages" DROP CONSTRAINT "FK_315b745a0b22dbc26cdb33ea596"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "FK_b1f120110cbed36432933d387d4"`);
        await queryRunner.query(`ALTER TABLE "edm_document_routes" DROP CONSTRAINT "FK_83e4e52bfe54b62e2fec2844563"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_deed290f1b3b94f901d321a6781"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_6d875d41ecb59952cf306d1228d"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_b8bf993005538aed05a0903c182"`);
        await queryRunner.query(`ALTER TABLE "edm_documents" DROP CONSTRAINT "FK_e40e6c1adb9151892020545d241"`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" DROP CONSTRAINT "FK_3bcd0bf9b7cb046ce5d71b057a6"`);
        await queryRunner.query(`ALTER TABLE "edm_document_kinds" DROP CONSTRAINT "FK_904360fe69c9f60910fb7cef217"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_2c2540c0d341c8e20048681f4c3"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_707a5642f0c835dbc89e603cbd5"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_1d312a094ffbc86e70c8893854d"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_9030ba74cb54f3c65fcf309570f"`);
        await queryRunner.query(`ALTER TABLE "iam_delegations" DROP CONSTRAINT "FK_8946ca43f41b4fcbc725a7f8d1c"`);
        await queryRunner.query(`ALTER TABLE "gis_features" DROP CONSTRAINT "FK_48ba677bd3fd44b3a6691a8c2d8"`);
        await queryRunner.query(`ALTER TABLE "gis_features" DROP CONSTRAINT "FK_90483a9d81a0cbed09b25f6deef"`);
        await queryRunner.query(`ALTER TABLE "gis_features" DROP CONSTRAINT "FK_5268fa7dbaf156831ed517f3759"`);
        await queryRunner.query(`ALTER TABLE "gis_layers" DROP CONSTRAINT "FK_c89661cb27502cbddbf498652dd"`);
        await queryRunner.query(`ALTER TABLE "gis_layers" DROP CONSTRAINT "FK_1f5043e3a28bb9e7ef52db78ba7"`);
        await queryRunner.query(`ALTER TABLE "bulk_import_operations" DROP CONSTRAINT "FK_85c062412f52428eb4ac1415b46"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_9d207f670875c015e66e25bfe0b"`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP CONSTRAINT "FK_93e336d1c079edb2cecd9c8f599"`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" DROP COLUMN "on_behalf_of_user_id"`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" DROP COLUMN "actor_user_id"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "org_unit_id"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "business_role"`);
        await queryRunner.query(`DROP TABLE "business_role_permission_profiles"`);
        await queryRunner.query(`DROP TABLE "iam_business_roles"`);
        await queryRunner.query(`DROP TABLE "permission_profiles"`);
        await queryRunner.query(`DROP TABLE "edm_alerts"`);
        await queryRunner.query(`DROP TABLE "edm_document_replies"`);
        await queryRunner.query(`DROP TABLE "edm_document_registry_sequences"`);
        await queryRunner.query(`DROP TABLE "edm_document_task_links"`);
        await queryRunner.query(`DROP TABLE "edm_document_timeline_events"`);
        await queryRunner.query(`DROP TABLE "edm_document_template_fields"`);
        await queryRunner.query(`DROP TABLE "edm_document_templates"`);
        await queryRunner.query(`DROP TABLE "edm_registration_journal"`);
        await queryRunner.query(`DROP TABLE "edm_route_templates"`);
        await queryRunner.query(`DROP TABLE "edm_route_template_stages"`);
        await queryRunner.query(`DROP TABLE "edm_saved_filters"`);
        await queryRunner.query(`DROP TABLE "edm_stage_actions"`);
        await queryRunner.query(`DROP TABLE "edm_route_stages"`);
        await queryRunner.query(`DROP TABLE "edm_document_routes"`);
        await queryRunner.query(`DROP TABLE "edm_documents"`);
        await queryRunner.query(`DROP TABLE "edm_document_kinds"`);
        await queryRunner.query(`DROP TABLE "iam_delegations"`);
        await queryRunner.query(`DROP TABLE "gis_features"`);
        await queryRunner.query(`DROP TYPE "public"."gis_features_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."gis_features_severity_enum"`);
        await queryRunner.query(`DROP TABLE "gis_layers"`);
        await queryRunner.query(`DROP TYPE "public"."gis_layers_type_enum"`);
        await queryRunner.query(`DROP TABLE "bulk_import_operations"`);
        await queryRunner.query(`DROP TABLE "org_units"`);
    }

}
